theme: jekyll-theme-leap-day
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - Library.md
  - reference-jekyll.md
  - lego_hiwi.md
  - project_work.md
